# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-19 09:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_id', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('contact', models.IntegerField()),
                ('u_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='proj_mngr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('contact', models.IntegerField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.admin')),
                ('u_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=250)),
                ('p_name', models.CharField(max_length=250)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.admin')),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.proj_mngr')),
            ],
        ),
        migrations.CreateModel(
            name='team_leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_id', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='team_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('contact', models.IntegerField()),
                ('u_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=250)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.projects')),
            ],
        ),
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_id', models.CharField(max_length=250)),
                ('desc', models.CharField(max_length=1000)),
                ('hours_worked', models.IntegerField()),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.team_member')),
            ],
        ),
        migrations.AddField(
            model_name='teams',
            name='work',
            field=models.ManyToManyField(to='website.work'),
        ),
        migrations.AddField(
            model_name='team_leader',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.teams'),
        ),
    ]
