# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-19 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_member',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
