# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-19 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170619_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team_leader',
            old_name='team',
            new_name='t_id',
        ),
        migrations.AddField(
            model_name='team_leader',
            name='m_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.proj_mngr'),
            preserve_default=False,
        ),
    ]
