# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-19 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20170619_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_admin',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='proj_mngr',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='team_member',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='main_admin',
            name='last_name',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proj_mngr',
            name='last_name',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team_member',
            name='last_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
