# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20170619_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='admin',
            field=models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, to='website.main_admin'),
        ),
    ]
