# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20170620_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.student'),
        ),
    ]
