# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20170620_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='team_student_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.projects')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.student')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.teams')),
            ],
        ),
    ]
