# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_team_student_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='hours_worked',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='s_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.student'),
        ),
        migrations.AlterField(
            model_name='work',
            name='t_id',
            field=models.ForeignKey(blank=True, default='0', on_delete=django.db.models.deletion.CASCADE, to='website.teams'),
        ),
        migrations.AlterField(
            model_name='work',
            name='w_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
