# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_work_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='s_id',
        ),
        migrations.RemoveField(
            model_name='work',
            name='t_id',
        ),
        migrations.DeleteModel(
            name='work',
        ),
    ]
