# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20170620_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='t_name',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
