# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_teams_t_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_member',
            name='t_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.teams'),
            preserve_default=False,
        ),
    ]
