# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20170621_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='t_members',
        ),
    ]
