# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_remove_teams_t_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='t_leader',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.team_leader'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teams',
            name='t_members',
            field=models.ManyToManyField(to='website.team_member'),
        ),
    ]
