# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 17:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20170621_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='u_id',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
