# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 17:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20170621_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proj_mngr',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
