# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 10:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20170622_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/%H/%M/%S/')),
            ],
        ),
        migrations.AlterField(
            model_name='work_log',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 22, 10, 0, 52, 92005)),
        ),
    ]
