# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 10:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20170622_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_log',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 22, 10, 9, 15, 235160)),
        ),
    ]
