# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 10:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20170622_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='file',
            field=models.FileField(upload_to='uploads/cms'),
        ),
        migrations.AlterField(
            model_name='work_log',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 22, 10, 25, 54, 403088)),
        ),
    ]
