# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 13:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20170622_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_log',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 22, 18, 45, 37, 703704)),
        ),
    ]
