# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_auto_20170622_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_log',
            name='date',
            field=models.DateField(),
        ),
    ]
