# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 13:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0032_auto_20170622_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('sender', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('valid', models.IntegerField(blank=True, default=1)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
