# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
