# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_auto_20170623_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='model_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
