# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-25 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_auto_20170624_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_log',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
