# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-25 18:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_auto_20170625_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
