# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-26 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_auto_20170626_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_admin',
            name='model_pic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='model_pic',
        ),
        migrations.AddField(
            model_name='main_admin',
            name='photo',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
