# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-27 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_team_member_l_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='l_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.team_leader'),
        ),
    ]
